apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-headless-service
  namespace: {{ .Values.common.namespace }}
spec:
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
  clusterIP: None
