apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-clusterIp
  namespace: {{ .Values.namespace.todoapp.name }}
spec:
  type: ClusterIP
  selector:
    app: todoapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
