apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-pv
  namespace: {{ .Values.namespace.todoapp.name }}
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.persistentVolume.todoapp.capacity }}
  hostPath:
    path: /data/
