global:
 namespace: todoapp

namespace:
  todoapp:
    name: todoapp-helm

todoapp:
  secret:
      SECRET_KEY: QGUyKHl4KXYmdGdoM19zPTB5amEtaSFkcGVieHN6XmRnNDd4KS1rJmtxXzN6Zio5ZSoK
      DB_NAME: "YXBwX2RiCg=="
      DB_USER: "YXBwX3VzZXI="
      DB_PASSWORD: "MTIzNA=="
      DB_HOST: "bXlzcWwtMC5teXNxbC5teXNxbC5zdmMuY2x1c3Rlci5sb2NhbAo="
  resources:
      requests:
          cpu: "150m"
          memory: "256Mi"
      limits:
          cpu: "150m"
          memory: "256Mi"

  rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  affinity:
      nodeAffinity:
        key: app
        values:
          - "todoapp"


image:
  todoapp:
    repository: yikulyk404/todoapp
    tag: "4.0.1"

hpa:
  todoapp:
    minReplicas: 2
    maxReplicas: 5
    cpuUtilization: 70
    memoryUtilization: 70

persistentVolume:
  todoapp:
    capacity: "1Gi"

persistentVolumeClaim:
  todoapp:
    storage: "1Gi"

serviceAccount: todoapp
