mysql:
  service:
    ports:
      name: mysql
      port: 3306
    clusterIP: None

  secrets:
    MYSQL_ROOT_PASSWORD: "1234"
    MYSQL_USER: "app_user"
    MYSQL_PASSWORD: "1234"

  statefulSet:
    replicas: 2
    name: mysql
    repository: mysql
    version: 8.0
    storage: 2Gi

    resources:
      requests:
        memory: 1Gi
        cpu: 500m

    livenessProbe:
      exec:
        command: ["mysqladmin", "ping"]
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5

    readinessProbe:
      exec:
        command: ["mysqladmin", "ping"]
      initialDelaySeconds: 5
      periodSeconds: 2
      timeoutSeconds: 1

    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "app"
                  operator: In
                  values:
                  - mysql
            topologyKey: "kubernetes.io/hostname"
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: "app"
                  operator: In
                  values:
                  - "mysql"

    tolerations:
      - key: "app"
        operator: "Equal"
        value: "mysql"
        effect: "NoSchedule"
