common:
  namespace: mysql
  image: mysql
  image_tag: 8.0

secrets:
  MYSQL_ROOT_PASSWORD: adminPass
  MYSQL_USER: app_user
  MYSQL_PASSWORD: adminPass

statefulset:
  replicas: 2
  resources:
    requests:
      cpu: 400m
      memory: 1Gi
  tolerations:
    key: app
    operator: Equal
    value: mysql
    effect: NoSchedule
  volumeClaimTemplates:
    spec:
      resources:
        requests:
          storage: 2Gi
  affinity:
    podAntiAffinity:
      matchExpressions:
        key: app
        operator: In
        values: mysql
    nodeAffinity:
      matchExpressions:
        key: app
        operator: In
        values: mysql