mysql:
  namespace: mysql

  replicas: 2
  image:
    repo: mysql
    tag: "8.0"
  port: 3306

  secret:
    MYSQL_ROOT_PASSWORD: "MTIzNA==" # Base64 encoding for "1234"
    MYSQL_USER: "YXBwX3VzZXI=" # Base64 encoding for "app_user"
    MYSQL_PASSWORD: "MTIzNA==" # Base64 encoding for "1234"

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
      storage: 2Gi
    limits:
      cpu: 500m
      memory: 1Gi

  affinity:
    key: "app"
    value: "mysql"

  tolerations:
    key: "app"
    value: "mysql"
