
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc
  namespace: {{ .Values.common.namespace }}
spec:
  volumeName: pv-data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.requests.storage }}