common:
  namespace: todoapp
  image: ikulyk404/todoapp
  image_tag: 4.0.1

secrets:
  SECRET_KEY: QGUyKHl4KXYmdGdoM19zPTB5amEtaSFkcGVieHN6XmRnNDd4KS1rJmtxXzN6Zio5ZSoK
  DB_NAME: app_db
  DB_USER: app_user
  DB_PASSWORD: userPass
  DB_HOST: mysql-0.mysql.mysql.svc.cluster.local

resources:
  requests:
    memory: 512Mi
    cpu: "200m"
  limits:
    memory: "512Mi"
    cpu: "200m"

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

nodeAffinityParameters:
  weight: 1
  key: app
  operator: In
  values: todoapp

hpa:
  minReplicas: 2
  maxReplicas: 5
  averageUtilization_CPU: 70
  averageUtilization_Memory: 70

pv:
  capacity:
    storage: 1Gi

pvc:
  requests:
    storage: 1Gi