apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name}}-clusterip-service
  namespace: {{ .Values.common.namespace }}
spec:
  type: ClusterIP
  selector:
    app: todoapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
