apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
{{- range $k, $v := .Values.todoapp.secret }}
  {{ $k | upper }}: {{ $v | b64enc | quote }}
 {{- end }}
